<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-08-11T05:34:06Z" name="Suite" finished-at="2021-08-11T05:34:13Z" duration-ms="7145">
    <groups>
    </groups>
    <test started-at="2021-08-11T05:34:06Z" name="Test" finished-at="2021-08-11T05:34:13Z" duration-ms="7145">
      <class name="june2021.qaautomation.APITest">
        <test-method is-config="true" signature="login()[pri:0, instance:june2021.qaautomation.APITest@226eba67]" started-at="2021-08-11T05:34:00Z" name="login" finished-at="2021-08-11T05:34:06Z" duration-ms="5881" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="test()[pri:0, instance:june2021.qaautomation.APITest@226eba67]" started-at="2021-08-11T05:34:06Z" name="test" finished-at="2021-08-11T05:34:06Z" duration-ms="54" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method signature="testConfigurationAPI()[pri:0, instance:june2021.qaautomation.APITest@226eba67]" started-at="2021-08-11T05:34:06Z" name="testConfigurationAPI" finished-at="2021-08-11T05:34:08Z" duration-ms="2169" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [USD] but found [INR]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [USD] but found [INR]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at june2021.qaautomation.APITest.testConfigurationAPI(APITest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testConfigurationAPI -->
        <test-method signature="testDashboardAPI()[pri:0, instance:june2021.qaautomation.APITest@226eba67]" started-at="2021-08-11T05:34:08Z" name="testDashboardAPI" finished-at="2021-08-11T05:34:12Z" duration-ms="3263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDashboardAPI -->
        <test-method signature="testInvalidCredentials()[pri:0, instance:june2021.qaautomation.APITest@226eba67]" started-at="2021-08-11T05:34:12Z" name="testInvalidCredentials" finished-at="2021-08-11T05:34:13Z" duration-ms="1613" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidCredentials -->
      </class> <!-- june2021.qaautomation.APITest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
